// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/runtime/rpc/proto/hostapi.proto

// Package glyphux.rpc.v1 is the Tier-C (PRD §8.1) wire contract between the
// host process (glyphuxd) and an out-of-process RPC plugin subprocess. Two
// services, one per direction of the "go-plugin model" (PRD §8.1, §10.3):
//
//   - HostAPI is served BY THE HOST, called BY THE PLUGIN. It is the gRPC
//     transport for pkg/sdk.HostAPI (PRD §8.3's unified extension contract) —
//     only the methods this slice wires up (Store, Emit, AllowsNetworkHost)
//     are exposed; every RPC here delegates to a real sdk.HostAPI value,
//     which is where PRD §10.3's boundary enforcement ("stripped of anything
//     it did not declare") actually lives — this proto layer adds no gating
//     of its own, it just carries sdk.HostAPI's existing capability-gated
//     errors across the process boundary as gRPC status errors.
//   - Plugin is served BY THE PLUGIN SUBPROCESS, called BY THE HOST. Register
//     is the plugin's entry point (mirrors the conceptual
//     Plugin.Register(host HostAPI) shape from PRD §8.3) — the host calls it
//     once the plugin's gRPC server is confirmed listening, and the plugin
//     subprocess is expected to call back into HostAPI during its handling
//     of Register, exactly as a real Tier-C plugin would during startup.

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreGetRequest) Reset() {
	*x = StoreGetRequest{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGetRequest) ProtoMessage() {}

func (x *StoreGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreGetRequest.ProtoReflect.Descriptor instead.
func (*StoreGetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{0}
}

func (x *StoreGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StoreGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreGetResponse) Reset() {
	*x = StoreGetResponse{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGetResponse) ProtoMessage() {}

func (x *StoreGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreGetResponse.ProtoReflect.Descriptor instead.
func (*StoreGetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{1}
}

func (x *StoreGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StoreGetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StoreSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSetRequest) Reset() {
	*x = StoreSetRequest{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSetRequest) ProtoMessage() {}

func (x *StoreSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSetRequest.ProtoReflect.Descriptor instead.
func (*StoreSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{2}
}

func (x *StoreSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StoreSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSetResponse) Reset() {
	*x = StoreSetResponse{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSetResponse) ProtoMessage() {}

func (x *StoreSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSetResponse.ProtoReflect.Descriptor instead.
func (*StoreSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{3}
}

type StoreDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDeleteRequest) Reset() {
	*x = StoreDeleteRequest{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDeleteRequest) ProtoMessage() {}

func (x *StoreDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDeleteRequest.ProtoReflect.Descriptor instead.
func (*StoreDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{4}
}

func (x *StoreDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StoreDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDeleteResponse) Reset() {
	*x = StoreDeleteResponse{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDeleteResponse) ProtoMessage() {}

func (x *StoreDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDeleteResponse.ProtoReflect.Descriptor instead.
func (*StoreDeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{5}
}

type EmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{6}
}

func (x *EmitRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *EmitRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{7}
}

type AllowsNetworkHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowsNetworkHostRequest) Reset() {
	*x = AllowsNetworkHostRequest{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowsNetworkHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowsNetworkHostRequest) ProtoMessage() {}

func (x *AllowsNetworkHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowsNetworkHostRequest.ProtoReflect.Descriptor instead.
func (*AllowsNetworkHostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{8}
}

func (x *AllowsNetworkHostRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type AllowsNetworkHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowsNetworkHostResponse) Reset() {
	*x = AllowsNetworkHostResponse{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowsNetworkHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowsNetworkHostResponse) ProtoMessage() {}

func (x *AllowsNetworkHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowsNetworkHostResponse.ProtoReflect.Descriptor instead.
func (*AllowsNetworkHostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{9}
}

func (x *AllowsNetworkHostResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// arg carries mode-specific data — e.g. for "network-check", the host
	// name to query AllowsNetworkHost with.
	Arg           string `protobuf:"bytes,2,opt,name=arg,proto3" json:"arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RegisterRequest) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           []string               `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterResponse) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_runtime_rpc_proto_hostapi_proto protoreflect.FileDescriptor

const file_pkg_runtime_rpc_proto_hostapi_proto_rawDesc = "" +
	"\n" +
	"#pkg/runtime/rpc/proto/hostapi.proto\x12\x0eglyphux.rpc.v1\"#\n" +
	"\x0fStoreGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"8\n" +
	"\x10StoreGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"9\n" +
	"\x0fStoreSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x12\n" +
	"\x10StoreSetResponse\"&\n" +
	"\x12StoreDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x15\n" +
	"\x13StoreDeleteResponse\"=\n" +
	"\vEmitRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x0e\n" +
	"\fEmitResponse\".\n" +
	"\x18AllowsNetworkHostRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"5\n" +
	"\x19AllowsNetworkHostResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"7\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x10\n" +
	"\x03arg\x18\x02 \x01(\tR\x03arg\"J\n" +
	"\x10RegisterResponse\x12\x10\n" +
	"\x03log\x18\x01 \x03(\tR\x03log\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xac\x03\n" +
	"\aHostAPI\x12M\n" +
	"\bStoreGet\x12\x1f.glyphux.rpc.v1.StoreGetRequest\x1a .glyphux.rpc.v1.StoreGetResponse\x12M\n" +
	"\bStoreSet\x12\x1f.glyphux.rpc.v1.StoreSetRequest\x1a .glyphux.rpc.v1.StoreSetResponse\x12V\n" +
	"\vStoreDelete\x12\".glyphux.rpc.v1.StoreDeleteRequest\x1a#.glyphux.rpc.v1.StoreDeleteResponse\x12A\n" +
	"\x04Emit\x12\x1b.glyphux.rpc.v1.EmitRequest\x1a\x1c.glyphux.rpc.v1.EmitResponse\x12h\n" +
	"\x11AllowsNetworkHost\x12(.glyphux.rpc.v1.AllowsNetworkHostRequest\x1a).glyphux.rpc.v1.AllowsNetworkHostResponse2W\n" +
	"\x06Plugin\x12M\n" +
	"\bRegister\x12\x1f.glyphux.rpc.v1.RegisterRequest\x1a .glyphux.rpc.v1.RegisterResponseB2Z0github.com/glyphux/glyphux/pkg/runtime/rpc/rpcpbb\x06proto3"

var (
	file_pkg_runtime_rpc_proto_hostapi_proto_rawDescOnce sync.Once
	file_pkg_runtime_rpc_proto_hostapi_proto_rawDescData []byte
)

func file_pkg_runtime_rpc_proto_hostapi_proto_rawDescGZIP() []byte {
	file_pkg_runtime_rpc_proto_hostapi_proto_rawDescOnce.Do(func() {
		file_pkg_runtime_rpc_proto_hostapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_runtime_rpc_proto_hostapi_proto_rawDesc), len(file_pkg_runtime_rpc_proto_hostapi_proto_rawDesc)))
	})
	return file_pkg_runtime_rpc_proto_hostapi_proto_rawDescData
}

var file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_runtime_rpc_proto_hostapi_proto_goTypes = []any{
	(*StoreGetRequest)(nil),           // 0: glyphux.rpc.v1.StoreGetRequest
	(*StoreGetResponse)(nil),          // 1: glyphux.rpc.v1.StoreGetResponse
	(*StoreSetRequest)(nil),           // 2: glyphux.rpc.v1.StoreSetRequest
	(*StoreSetResponse)(nil),          // 3: glyphux.rpc.v1.StoreSetResponse
	(*StoreDeleteRequest)(nil),        // 4: glyphux.rpc.v1.StoreDeleteRequest
	(*StoreDeleteResponse)(nil),       // 5: glyphux.rpc.v1.StoreDeleteResponse
	(*EmitRequest)(nil),               // 6: glyphux.rpc.v1.EmitRequest
	(*EmitResponse)(nil),              // 7: glyphux.rpc.v1.EmitResponse
	(*AllowsNetworkHostRequest)(nil),  // 8: glyphux.rpc.v1.AllowsNetworkHostRequest
	(*AllowsNetworkHostResponse)(nil), // 9: glyphux.rpc.v1.AllowsNetworkHostResponse
	(*RegisterRequest)(nil),           // 10: glyphux.rpc.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 11: glyphux.rpc.v1.RegisterResponse
}
var file_pkg_runtime_rpc_proto_hostapi_proto_depIdxs = []int32{
	0,  // 0: glyphux.rpc.v1.HostAPI.StoreGet:input_type -> glyphux.rpc.v1.StoreGetRequest
	2,  // 1: glyphux.rpc.v1.HostAPI.StoreSet:input_type -> glyphux.rpc.v1.StoreSetRequest
	4,  // 2: glyphux.rpc.v1.HostAPI.StoreDelete:input_type -> glyphux.rpc.v1.StoreDeleteRequest
	6,  // 3: glyphux.rpc.v1.HostAPI.Emit:input_type -> glyphux.rpc.v1.EmitRequest
	8,  // 4: glyphux.rpc.v1.HostAPI.AllowsNetworkHost:input_type -> glyphux.rpc.v1.AllowsNetworkHostRequest
	10, // 5: glyphux.rpc.v1.Plugin.Register:input_type -> glyphux.rpc.v1.RegisterRequest
	1,  // 6: glyphux.rpc.v1.HostAPI.StoreGet:output_type -> glyphux.rpc.v1.StoreGetResponse
	3,  // 7: glyphux.rpc.v1.HostAPI.StoreSet:output_type -> glyphux.rpc.v1.StoreSetResponse
	5,  // 8: glyphux.rpc.v1.HostAPI.StoreDelete:output_type -> glyphux.rpc.v1.StoreDeleteResponse
	7,  // 9: glyphux.rpc.v1.HostAPI.Emit:output_type -> glyphux.rpc.v1.EmitResponse
	9,  // 10: glyphux.rpc.v1.HostAPI.AllowsNetworkHost:output_type -> glyphux.rpc.v1.AllowsNetworkHostResponse
	11, // 11: glyphux.rpc.v1.Plugin.Register:output_type -> glyphux.rpc.v1.RegisterResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_runtime_rpc_proto_hostapi_proto_init() }
func file_pkg_runtime_rpc_proto_hostapi_proto_init() {
	if File_pkg_runtime_rpc_proto_hostapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_runtime_rpc_proto_hostapi_proto_rawDesc), len(file_pkg_runtime_rpc_proto_hostapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_runtime_rpc_proto_hostapi_proto_goTypes,
		DependencyIndexes: file_pkg_runtime_rpc_proto_hostapi_proto_depIdxs,
		MessageInfos:      file_pkg_runtime_rpc_proto_hostapi_proto_msgTypes,
	}.Build()
	File_pkg_runtime_rpc_proto_hostapi_proto = out.File
	file_pkg_runtime_rpc_proto_hostapi_proto_goTypes = nil
	file_pkg_runtime_rpc_proto_hostapi_proto_depIdxs = nil
}
