// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pkg/runtime/rpc/proto/hostapi.proto

// Package glyphux.rpc.v1 is the Tier-C (PRD §8.1) wire contract between the
// host process (glyphuxd) and an out-of-process RPC plugin subprocess. Two
// services, one per direction of the "go-plugin model" (PRD §8.1, §10.3):
//
//   - HostAPI is served BY THE HOST, called BY THE PLUGIN. It is the gRPC
//     transport for pkg/sdk.HostAPI (PRD §8.3's unified extension contract) —
//     only the methods this slice wires up (Store, Emit, AllowsNetworkHost)
//     are exposed; every RPC here delegates to a real sdk.HostAPI value,
//     which is where PRD §10.3's boundary enforcement ("stripped of anything
//     it did not declare") actually lives — this proto layer adds no gating
//     of its own, it just carries sdk.HostAPI's existing capability-gated
//     errors across the process boundary as gRPC status errors.
//   - Plugin is served BY THE PLUGIN SUBPROCESS, called BY THE HOST. Register
//     is the plugin's entry point (mirrors the conceptual
//     Plugin.Register(host HostAPI) shape from PRD §8.3) — the host calls it
//     once the plugin's gRPC server is confirmed listening, and the plugin
//     subprocess is expected to call back into HostAPI during its handling
//     of Register, exactly as a real Tier-C plugin would during startup.

package rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAPI_StoreGet_FullMethodName          = "/glyphux.rpc.v1.HostAPI/StoreGet"
	HostAPI_StoreSet_FullMethodName          = "/glyphux.rpc.v1.HostAPI/StoreSet"
	HostAPI_StoreDelete_FullMethodName       = "/glyphux.rpc.v1.HostAPI/StoreDelete"
	HostAPI_Emit_FullMethodName              = "/glyphux.rpc.v1.HostAPI/Emit"
	HostAPI_AllowsNetworkHost_FullMethodName = "/glyphux.rpc.v1.HostAPI/AllowsNetworkHost"
)

// HostAPIClient is the client API for HostAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostAPI is the host-side service a plugin subprocess dials to reach its
// capability-gated pkg/sdk.HostAPI. Store* methods correspond to
// sdk.HostAPI.Store() (always present — no capability gates persistence,
// see pkg/sdk/host.go). Emit corresponds to sdk.HostAPI.Emit, gated on the
// "events:emit" api scope by the underlying sdk.HostAPI — a plugin whose
// manifest didn't declare it gets a gRPC error, not a silent no-op.
// AllowsNetworkHost corresponds to sdk.HostAPI.AllowsNetworkHost, the
// network-allowlist decision primitive (PRD §10.4, "allowlisted network").
type HostAPIClient interface {
	StoreGet(ctx context.Context, in *StoreGetRequest, opts ...grpc.CallOption) (*StoreGetResponse, error)
	StoreSet(ctx context.Context, in *StoreSetRequest, opts ...grpc.CallOption) (*StoreSetResponse, error)
	StoreDelete(ctx context.Context, in *StoreDeleteRequest, opts ...grpc.CallOption) (*StoreDeleteResponse, error)
	Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error)
	AllowsNetworkHost(ctx context.Context, in *AllowsNetworkHostRequest, opts ...grpc.CallOption) (*AllowsNetworkHostResponse, error)
}

type hostAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAPIClient(cc grpc.ClientConnInterface) HostAPIClient {
	return &hostAPIClient{cc}
}

func (c *hostAPIClient) StoreGet(ctx context.Context, in *StoreGetRequest, opts ...grpc.CallOption) (*StoreGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreGetResponse)
	err := c.cc.Invoke(ctx, HostAPI_StoreGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) StoreSet(ctx context.Context, in *StoreSetRequest, opts ...grpc.CallOption) (*StoreSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreSetResponse)
	err := c.cc.Invoke(ctx, HostAPI_StoreSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) StoreDelete(ctx context.Context, in *StoreDeleteRequest, opts ...grpc.CallOption) (*StoreDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreDeleteResponse)
	err := c.cc.Invoke(ctx, HostAPI_StoreDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, HostAPI_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) AllowsNetworkHost(ctx context.Context, in *AllowsNetworkHostRequest, opts ...grpc.CallOption) (*AllowsNetworkHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllowsNetworkHostResponse)
	err := c.cc.Invoke(ctx, HostAPI_AllowsNetworkHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAPIServer is the server API for HostAPI service.
// All implementations must embed UnimplementedHostAPIServer
// for forward compatibility.
//
// HostAPI is the host-side service a plugin subprocess dials to reach its
// capability-gated pkg/sdk.HostAPI. Store* methods correspond to
// sdk.HostAPI.Store() (always present — no capability gates persistence,
// see pkg/sdk/host.go). Emit corresponds to sdk.HostAPI.Emit, gated on the
// "events:emit" api scope by the underlying sdk.HostAPI — a plugin whose
// manifest didn't declare it gets a gRPC error, not a silent no-op.
// AllowsNetworkHost corresponds to sdk.HostAPI.AllowsNetworkHost, the
// network-allowlist decision primitive (PRD §10.4, "allowlisted network").
type HostAPIServer interface {
	StoreGet(context.Context, *StoreGetRequest) (*StoreGetResponse, error)
	StoreSet(context.Context, *StoreSetRequest) (*StoreSetResponse, error)
	StoreDelete(context.Context, *StoreDeleteRequest) (*StoreDeleteResponse, error)
	Emit(context.Context, *EmitRequest) (*EmitResponse, error)
	AllowsNetworkHost(context.Context, *AllowsNetworkHostRequest) (*AllowsNetworkHostResponse, error)
	mustEmbedUnimplementedHostAPIServer()
}

// UnimplementedHostAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAPIServer struct{}

func (UnimplementedHostAPIServer) StoreGet(context.Context, *StoreGetRequest) (*StoreGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreGet not implemented")
}
func (UnimplementedHostAPIServer) StoreSet(context.Context, *StoreSetRequest) (*StoreSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreSet not implemented")
}
func (UnimplementedHostAPIServer) StoreDelete(context.Context, *StoreDeleteRequest) (*StoreDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreDelete not implemented")
}
func (UnimplementedHostAPIServer) Emit(context.Context, *EmitRequest) (*EmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedHostAPIServer) AllowsNetworkHost(context.Context, *AllowsNetworkHostRequest) (*AllowsNetworkHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllowsNetworkHost not implemented")
}
func (UnimplementedHostAPIServer) mustEmbedUnimplementedHostAPIServer() {}
func (UnimplementedHostAPIServer) testEmbeddedByValue()                 {}

// UnsafeHostAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAPIServer will
// result in compilation errors.
type UnsafeHostAPIServer interface {
	mustEmbedUnimplementedHostAPIServer()
}

func RegisterHostAPIServer(s grpc.ServiceRegistrar, srv HostAPIServer) {
	// If the following call panics, it indicates UnimplementedHostAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAPI_ServiceDesc, srv)
}

func _HostAPI_StoreGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).StoreGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_StoreGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).StoreGet(ctx, req.(*StoreGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_StoreSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).StoreSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_StoreSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).StoreSet(ctx, req.(*StoreSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_StoreDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).StoreDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_StoreDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).StoreDelete(ctx, req.(*StoreDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).Emit(ctx, req.(*EmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_AllowsNetworkHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowsNetworkHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).AllowsNetworkHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_AllowsNetworkHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).AllowsNetworkHost(ctx, req.(*AllowsNetworkHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAPI_ServiceDesc is the grpc.ServiceDesc for HostAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "glyphux.rpc.v1.HostAPI",
	HandlerType: (*HostAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreGet",
			Handler:    _HostAPI_StoreGet_Handler,
		},
		{
			MethodName: "StoreSet",
			Handler:    _HostAPI_StoreSet_Handler,
		},
		{
			MethodName: "StoreDelete",
			Handler:    _HostAPI_StoreDelete_Handler,
		},
		{
			MethodName: "Emit",
			Handler:    _HostAPI_Emit_Handler,
		},
		{
			MethodName: "AllowsNetworkHost",
			Handler:    _HostAPI_AllowsNetworkHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/runtime/rpc/proto/hostapi.proto",
}

const (
	Plugin_Register_FullMethodName = "/glyphux.rpc.v1.Plugin/Register"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plugin is the plugin-subprocess-side service the host dials once the
// subprocess signals it is listening. Register is the subprocess's single
// entry point for this slice's test fixture: the host calls it with a mode
// string selecting fixture behavior (see pkg/runtime/rpc/testdata/fixtureplugin),
// and the fixture's handler is expected to call back into HostAPI (above)
// during its handling of Register — proving a real, bidirectional,
// cross-process gRPC round trip, not a one-way call.
type PluginClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Plugin_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
//
// Plugin is the plugin-subprocess-side service the host dials once the
// subprocess signals it is listening. Register is the subprocess's single
// entry point for this slice's test fixture: the host calls it with a mode
// string selecting fixture behavior (see pkg/runtime/rpc/testdata/fixtureplugin),
// and the fixture's handler is expected to call back into HostAPI (above)
// during its handling of Register — proving a real, bidirectional,
// cross-process gRPC round trip, not a one-way call.
type PluginServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "glyphux.rpc.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Plugin_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/runtime/rpc/proto/hostapi.proto",
}
