package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/glyphux/glyphux/internal/graphql/generated"
)

// ContentTypes is the resolver for the contentTypes field. It mirrors GET
// /api/v0/content-types — publicly readable, no capability required.
func (r *queryResolver) ContentTypes(ctx context.Context) ([]*generated.ContentTypeDef, error) {
	comp, err := r.compositions.Load(ctx)
	if err != nil {
		return nil, r.mapCompositionError(err)
	}
	return contentTypeDefs(comp), nil
}

// ContentItem is the resolver for the contentItem field. It mirrors
// handleContentGet in internal/api/api.go: drafts are visible only to
// callers holding content:read_drafts, and locale resolves localized
// fields to a single value.
func (r *queryResolver) ContentItem(ctx context.Context, typeArg string, id string, locale *string) (*generated.ContentItem, error) {
	item, err := r.getContentItem(ctx, typeArg, id, locale)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	return contentItemModel(item), nil
}

// ContentItems is the resolver for the contentItems field. It mirrors
// handleContentList in internal/api/api.go.
func (r *queryResolver) ContentItems(ctx context.Context, typeArg string, locale *string) ([]*generated.ContentItem, error) {
	items, err := r.listContentItems(ctx, typeArg, locale)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	out := make([]*generated.ContentItem, len(items))
	for i, item := range items {
		out[i] = contentItemModel(item)
	}
	return out, nil
}

// ContentVersions is the resolver for the contentVersions field. It mirrors
// handleContentListVersions in internal/api/api.go — publicly readable,
// like REST's GET .../versions.
func (r *queryResolver) ContentVersions(ctx context.Context, typeArg string, id string) ([]*generated.ContentVersion, error) {
	versions, err := r.content.ListVersions(ctx, typeArg, id)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	out := make([]*generated.ContentVersion, len(versions))
	for i, v := range versions {
		out[i] = &generated.ContentVersion{
			Version:   v.Version,
			Data:      v.Data,
			Status:    v.Status,
			CreatedAt: formatTime(v.CreatedAt),
		}
	}
	return out, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
