package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/glyphux/glyphux/internal/graphql/generated"
)

// ContentTypes is the resolver for the contentTypes field. It mirrors GET
// /api/v0/content-types — publicly readable, no capability required.
func (r *queryResolver) ContentTypes(ctx context.Context) ([]*generated.ContentTypeDef, error) {
	comp, err := r.compositions.Load(ctx)
	if err != nil {
		return nil, r.mapCompositionError(err)
	}
	return contentTypeDefs(comp), nil
}

// ContentItem is the resolver for the contentItem field. It mirrors
// handleContentGet in internal/api/api.go: drafts are visible only to
// callers holding content:read_drafts, and locale resolves localized
// fields to a single value.
func (r *queryResolver) ContentItem(ctx context.Context, typeArg string, id string, locale *string) (*generated.ContentItem, error) {
	item, err := r.getContentItem(ctx, typeArg, id, locale)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	return contentItemModel(item), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
