package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/glyphux/glyphux/internal/graphql/generated"
	"github.com/glyphux/glyphux/internal/permission"
)

// CreateContentItem is the resolver for the createContentItem field. It
// mirrors handleContentCreate in internal/api/api.go: requires
// content:write, same as REST.
func (r *mutationResolver) CreateContentItem(ctx context.Context, typeArg string, data map[string]any) (*generated.ContentItem, error) {
	if _, err := requireCapability(ctx, permission.ContentWrite); err != nil {
		return nil, err
	}
	item, err := r.content.Create(ctx, typeArg, data)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	return contentItemModel(item), nil
}

// UpdateContentItem is the resolver for the updateContentItem field. It
// mirrors handleContentUpdate: requires content:write.
func (r *mutationResolver) UpdateContentItem(ctx context.Context, typeArg string, id string, data map[string]any) (*generated.ContentItem, error) {
	if _, err := requireCapability(ctx, permission.ContentWrite); err != nil {
		return nil, err
	}
	item, err := r.content.Update(ctx, typeArg, id, data)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	return contentItemModel(item), nil
}

// DeleteContentItem is the resolver for the deleteContentItem field. It
// mirrors handleContentDelete: requires content:write.
func (r *mutationResolver) DeleteContentItem(ctx context.Context, typeArg string, id string) (bool, error) {
	if _, err := requireCapability(ctx, permission.ContentWrite); err != nil {
		return false, err
	}
	if err := r.content.Delete(ctx, typeArg, id); err != nil {
		return false, r.mapContentError(err)
	}
	return true, nil
}

// PublishContentItem is the resolver for the publishContentItem field. It
// mirrors handleContentPublish: requires content:publish, which — unlike
// content:write — editor does NOT hold (see internal/permission).
func (r *mutationResolver) PublishContentItem(ctx context.Context, typeArg string, id string) (*generated.ContentItem, error) {
	if _, err := requireCapability(ctx, permission.ContentPublish); err != nil {
		return nil, err
	}
	item, err := r.content.Publish(ctx, typeArg, id)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	return contentItemModel(item), nil
}

// UnpublishContentItem is the resolver for the unpublishContentItem field.
// It mirrors handleContentUnpublish: requires content:publish.
func (r *mutationResolver) UnpublishContentItem(ctx context.Context, typeArg string, id string) (*generated.ContentItem, error) {
	if _, err := requireCapability(ctx, permission.ContentPublish); err != nil {
		return nil, err
	}
	item, err := r.content.Unpublish(ctx, typeArg, id)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	return contentItemModel(item), nil
}

// RollbackContentItem is the resolver for the rollbackContentItem field. It
// mirrors handleContentRollback: requires content:write.
func (r *mutationResolver) RollbackContentItem(ctx context.Context, typeArg string, id string, version int) (*generated.ContentItem, error) {
	if _, err := requireCapability(ctx, permission.ContentWrite); err != nil {
		return nil, err
	}
	item, err := r.content.Rollback(ctx, typeArg, id, version)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	return contentItemModel(item), nil
}

// DefineContentType is the resolver for the defineContentType field. It
// mirrors handleContentTypePut in internal/api/contenttypes.go: requires
// content_types:manage (admin-only).
func (r *mutationResolver) DefineContentType(ctx context.Context, name string, fields []*generated.FieldInput) (*generated.ContentTypeDef, error) {
	if _, err := requireCapability(ctx, permission.ContentTypesManage); err != nil {
		return nil, err
	}
	ct := contentTypeFromInput(fields)
	comp, err := r.compositions.DefineContentType(ctx, name, ct)
	if err != nil {
		return nil, r.mapContentTypeError(err)
	}
	return contentTypeDef(name, comp.ContentTypes[name]), nil
}

// RemoveContentType is the resolver for the removeContentType field. It
// mirrors handleContentTypeDelete: requires content_types:manage and
// applies the same delete guard — rejected with CONFLICT if items of that
// type still exist, so a removal never silently orphans content_items rows.
func (r *mutationResolver) RemoveContentType(ctx context.Context, name string) (bool, error) {
	if _, err := requireCapability(ctx, permission.ContentTypesManage); err != nil {
		return false, err
	}
	count, err := r.content.CountItems(ctx, name)
	if err != nil {
		r.log.Error("count content items", "error", err)
		return false, gqlErr("INTERNAL", "internal error")
	}
	if count > 0 {
		return false, gqlErr("CONFLICT", "content type has existing items; delete or migrate them first")
	}
	if _, err := r.compositions.RemoveContentType(ctx, name); err != nil {
		return false, r.mapContentTypeError(err)
	}
	return true, nil
}

// DeleteMediaItem is the resolver for the deleteMediaItem field. It mirrors
// handleMediaDelete in internal/api/media.go: requires media:write.
func (r *mutationResolver) DeleteMediaItem(ctx context.Context, id string) (bool, error) {
	if _, err := requireCapability(ctx, permission.MediaWrite); err != nil {
		return false, err
	}
	if err := r.media.Delete(ctx, id); err != nil {
		return false, r.mapMediaError(err)
	}
	return true, nil
}

// ContentTypes is the resolver for the contentTypes field. It mirrors GET
// /api/v0/content-types — publicly readable, no capability required.
func (r *queryResolver) ContentTypes(ctx context.Context) ([]*generated.ContentTypeDef, error) {
	comp, err := r.compositions.Load(ctx)
	if err != nil {
		return nil, r.mapCompositionError(err)
	}
	return contentTypeDefs(comp), nil
}

// ContentItem is the resolver for the contentItem field. It mirrors
// handleContentGet in internal/api/api.go: drafts are visible only to
// callers holding content:read_drafts, and locale resolves localized
// fields to a single value.
func (r *queryResolver) ContentItem(ctx context.Context, typeArg string, id string, locale *string) (*generated.ContentItem, error) {
	item, err := r.getContentItem(ctx, typeArg, id, locale)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	return contentItemModel(item), nil
}

// ContentItems is the resolver for the contentItems field. It mirrors
// handleContentList in internal/api/api.go.
func (r *queryResolver) ContentItems(ctx context.Context, typeArg string, locale *string) ([]*generated.ContentItem, error) {
	items, err := r.listContentItems(ctx, typeArg, locale)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	out := make([]*generated.ContentItem, len(items))
	for i, item := range items {
		out[i] = contentItemModel(item)
	}
	return out, nil
}

// ContentVersions is the resolver for the contentVersions field. It mirrors
// handleContentListVersions in internal/api/api.go — publicly readable,
// like REST's GET .../versions.
func (r *queryResolver) ContentVersions(ctx context.Context, typeArg string, id string) ([]*generated.ContentVersion, error) {
	versions, err := r.content.ListVersions(ctx, typeArg, id)
	if err != nil {
		return nil, r.mapContentError(err)
	}
	out := make([]*generated.ContentVersion, len(versions))
	for i, v := range versions {
		out[i] = &generated.ContentVersion{
			Version:   v.Version,
			Data:      v.Data,
			Status:    v.Status,
			CreatedAt: formatTime(v.CreatedAt),
		}
	}
	return out, nil
}

// MediaItem is the resolver for the mediaItem field. It mirrors
// handleMediaGet — publicly readable, like REST.
func (r *queryResolver) MediaItem(ctx context.Context, id string) (*generated.MediaItem, error) {
	item, err := r.media.Get(ctx, id)
	if err != nil {
		return nil, r.mapMediaError(err)
	}
	return mediaItemModel(item), nil
}

// MediaItems is the resolver for the mediaItems field. It mirrors
// handleMediaList — publicly readable, like REST.
func (r *queryResolver) MediaItems(ctx context.Context) ([]*generated.MediaItem, error) {
	items, err := r.media.List(ctx)
	if err != nil {
		return nil, r.mapMediaError(err)
	}
	out := make([]*generated.MediaItem, len(items))
	for i, item := range items {
		out[i] = mediaItemModel(item)
	}
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
